# Generated by Django 4.2.4 on 2023-10-05 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliveryaddress'),
        ),
    ]
