# Generated by Django 4.2.4 on 2023-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_payment_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, default='pending', max_length=30, null=True),
        ),
    ]
