# Generated by Django 4.2.4 on 2023-10-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.EmailField(blank=True, max_length=245, null=True, unique=True),
        ),
    ]
