# Generated by Django 4.2.3 on 2023-07-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=245)),
                ('state', models.CharField(max_length=245)),
                ('city', models.CharField(max_length=245)),
                ('street', models.CharField(max_length=245)),
                ('postal', models.CharField(max_length=245)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.address'),
        ),
    ]
