# Generated by Django 4.2.4 on 2023-10-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=245, null=True, unique=True),
        ),
    ]
