# Generated by Django 4.2.3 on 2023-07-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_address_profile_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
